[[redirects]]
    from = "/"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/teamreg"
    to = "/teamreg/index.html"
    status = 200

[[redirects]]
    from = "/page3"
    to = "/page3/index.html"
    status = 200